env: # not working (see requirements.txt)
  name: Foraging-10x10-3p-3f-v1
  max_step: 25
  pomdp: False # TODO

network:
  name: gym_model
  num_state: 18 # TODO
  num_action: 6
  discrete_action: True
  gru: False # TODO
  has_collection_state_vector: True

strategy:
  name : openai_es
  init_sigma: 0.168 # TODO
  sigma_decay: 0.9999 # TODO
  learning_rate: 0.087 # TODO
  offspring_num: 96 # TODO
