env:
  name: simple_spread
  max_step: 100

network:
  name: gym_model
  num_state: 12
  num_action: 5
  discrete_action: True
  gru: False
  has_collection_state_vector: False

strategy:
  name : openai_es
  init_sigma: 0.2
  sigma_decay: 0.99999
  learning_rate: 0.0005
  offspring_num: 240