env:
  name: simple_speaker_listener
  max_step: 100

network:
  name: gym_model
  num_state: 14
  num_action: 3 
  discrete_action: True # TODO True or False? pettingzoo allows both.
  gru: False

strategy:
  name : openai_es
  init_sigma: 0.2 # TODO
  sigma_decay: 0.99999 # TODO
  learning_rate: 0.0005
  offspring_num: 240 # TODO
